## 1)Introduction to numpy 

In [1]:
import numpy as np 

0.21384191585136092

In [24]:
#use of random.random() functions in numpy 
np.random.random()

0.8152786445781908

In [58]:
# coin toss game
# np.random.random() can be considered as a probablity function ranging from 0 to 1 
if np.random.random() > 0.5:
    print('Heads')
else:
    print('Tails')
    

Tails


In [59]:
# np.arange(start,stop,step) gives ndarray with range lying between the starting and the ending points with certain steps
np.arange(1,5,1)

array([1, 2, 3, 4])

In [61]:
# np.linspace(start,stop,division) gives ndarray with float values ranging between the start and the stop values 
np.linspace(1,6,3)

array([1. , 3.5, 6. ])

# 2) Numpy Reshaping

In [65]:
arr1= np.array([[1,2],[3,4],[5,6]])

In [67]:
#arr1.size gives the size of the array or we can also say that it gives us the total elements present in the given array 
arr1.size

6

In [70]:
#arr1.shape() give the dimension of the matrix in the form of MXN
arr1.shape

(3, 2)

In [73]:
#arr1.reshape((M,N)) gives the reshaped dimension of a given array provided the total elements should satisfy 
arr1.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

# 3) numpy flattening 

In [75]:
arr = np.random.random((5,5))
arr

array([[0.26996182, 0.91938506, 0.34193021, 0.89186158, 0.83277914],
       [0.8143943 , 0.76188894, 0.24782286, 0.31722004, 0.61200847],
       [0.95134748, 0.79498393, 0.30445703, 0.22892355, 0.77123794],
       [0.97405359, 0.37493412, 0.40716164, 0.3020178 , 0.94521865],
       [0.96375689, 0.48504343, 0.28337912, 0.95989488, 0.44904853]])

In [76]:
# arr.flatten() combines any MXN matrix to single unit 
arr.flatten()

array([0.26996182, 0.91938506, 0.34193021, 0.89186158, 0.83277914,
       0.8143943 , 0.76188894, 0.24782286, 0.31722004, 0.61200847,
       0.95134748, 0.79498393, 0.30445703, 0.22892355, 0.77123794,
       0.97405359, 0.37493412, 0.40716164, 0.3020178 , 0.94521865,
       0.96375689, 0.48504343, 0.28337912, 0.95989488, 0.44904853])

## 4)Numpy arrays to list and vice versa

In [77]:
list1 = [1,2,3,4,5,6]
#converting to ndarray 
np.array(list1)

array([1, 2, 3, 4, 5, 6])

In [78]:
arr = np.random.random((5,5))
list2 = list(arr)
print(list2)

[array([0.37378146, 0.09818758, 0.32930499, 0.90877267, 0.53966733]), array([0.69536876, 0.90601721, 0.57763469, 0.97105771, 0.49225491]), array([0.76796256, 0.00277303, 0.5555182 , 0.96229885, 0.94408148]), array([0.46277791, 0.15397287, 0.03737467, 0.60963633, 0.33361714]), array([0.80293871, 0.28994437, 0.07444264, 0.91944724, 0.71921044])]


## 5) Numpy operations

In [80]:
arr1= np.array([1,2,3,4,5,6])

In [81]:
arr1 + 1

array([2, 3, 4, 5, 6, 7])

In [82]:
arr1 - 1

array([0, 1, 2, 3, 4, 5])

In [83]:
arr1 * 2

array([ 2,  4,  6,  8, 10, 12])

In [85]:
arr1 /2

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [86]:
arr1 % 2

array([1, 0, 1, 0, 1, 0], dtype=int32)

In [88]:
arr1 ** 2

array([ 1,  4,  9, 16, 25, 36])

In [90]:
arr1.mean()

3.5

In [93]:
np.median(arr1)

3.5

In [95]:
arr1.min()

1

In [98]:
arr1.max()

6

In [102]:
arr1.sum()

78

# 6) operations on arrays

In [122]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
arr3 = np.array([[7,8],[9,10],[11,12]])

In [106]:
arr1 + arr2 

array([[ 8, 10, 12],
       [14, 16, 18]])

In [118]:
arr1 - arr2

array([[-6, -6, -6],
       [-6, -6, -6]])

In [119]:
arr1 * arr2 

array([[ 7, 16, 27],
       [40, 55, 72]])

In [129]:
# dot product of two matrix 
print(arr1.dot(arr3))
# cross product of two matrix 
print(np.cross(arr1,arr2))

[[ 58  64]
 [139 154]]
[[-6 12 -6]
 [-6 12 -6]]


In [110]:
arr1.max()

6

In [113]:
arr1.max(axis = 0)

array([4, 5, 6])

In [114]:
arr1.min(axis = 1)

array([1, 4])

In [108]:
arr1.sum()

21

In [116]:
arr1.sum(axis = 0 )

array([5, 7, 9])

In [130]:
arr1.sum(axis = 1)

array([ 6, 15])

# array slicing and sorting 

In [139]:
arr1[0][0]# for 2-d array size 

1

In [144]:
arr1[:1]

array([[1, 2, 3]])

In [153]:
new_arr = np.array([1,2,3,4,5,6,9,8,7])
new_arr[0] #slicing for array size 1-d

1

In [149]:
new_arr[:3]

array([1, 2, 3])

In [150]:
new_arr[1:]

array([2, 3, 4, 5, 6])

In [152]:
new_arr[1:-1]

array([2, 3, 4, 5])

In [156]:
np.sort(new_arr,kind='mergesort')

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [158]:
np.sort(new_arr,kind='quicksort')

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [160]:
np.sort(arr1,axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [162]:
np.sort(arr1,axis=1)

array([[1, 2, 3],
       [4, 5, 6]])

# numpy merging 

In [174]:
#horizontal stacking and vertical stacking 
h_stack = np.hstack((arr1,arr2))

In [175]:
v_stack = np.vstack((arr1,arr2))

In [170]:
np.concatenate((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [172]:
np.concatenate((arr1,arr2),axis = 1)      #same as horizontal stacking

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [173]:
np.concatenate((arr1,arr2),axis = 0)     #same as vertical stacking 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# numpy spliting 

In [179]:
#horizontal spliting using hsplit function present in numpy in built library 
# format np.hsplit(array, division)
np.hsplit(h_stack,2)                       #horizontal spliting

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [181]:
np.vsplit(v_stack,2)                    #vertical spliting 

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [188]:
np.hsplit(v_stack,1)

[array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])]

In [191]:
np.vsplit(h_stack,2) 

[array([[1, 2, 3, 7, 8, 9]]), array([[ 4,  5,  6, 10, 11, 12]])]

# advantages of numpy than list 

In [195]:
ages = [53,45,87,12,10,11,18]
#voters eligibility criteria 
c = 0
for i in ages:
    if i >=18:
        print(i)
        c += 1
print('Eligible: ',c)

53
45
87
18
Eligible:  4


In [200]:
# how many people in the given list are eligible  to vote 
arr = np.array(ages)
arr[np.array(ages)>=18]

array([53, 45, 87, 18])

In [201]:
# count of people in given list 
len(arr[np.array(ages)>=18])

4

In [205]:
# even aged people
print(len(arr[np.array(ages)%2 == 0]))
print(arr[np.array(ages)%2 == 0])

3
[12 10 18]
